(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "expand-region")
(depends-on "better-defaults")
(depends-on "magit")
(depends-on "popwin")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")

(depends-on "helm")
(depends-on "helm-ls-git")
(depends-on "auto-complete")
(depends-on "smooth-scrolling")
(depends-on "smartparens")
(depends-on "flycheck")

(depends-on "ssh-config-mode")
(depends-on "yaml-mode")
(depends-on "haml-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "coffee-mode")
(depends-on "web-mode")

(depends-on "color-theme-sanityinc-tomorrow")
