(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "popwin")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")
(depends-on "yasnippet")

(depends-on "helm")
(depends-on "helm-ls-git")
(depends-on "auto-complete")
(depends-on "smooth-scrolling")
(depends-on "smartparens")
(depends-on "flycheck")
